version: '3'
services:
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./Frontend
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - SERVICE_NAME=frontend
      - ZOOKEPER_HOST=zoo
  node1:
    stop_grace_period: 0s
    build:
      dockerfile: Dockerfile
      context: ./Cluster
    ports:
      - "8081:8081"
    environment:
      - SERVER_PORT=8081
      - SERVICE_NAME=node1
      - ZOOKEPER_HOST=zoo
  node2:
    stop_grace_period: 0s
    build:
      dockerfile: Dockerfile
      context: ./Cluster
    ports:
      - "8082:8082"
    environment:
        - SERVER_PORT=8082
        - SERVICE_NAME=node2
        - ZOOKEPER_HOST=zoo
  node3:
    stop_grace_period: 0s
    build:
      dockerfile: Dockerfile
      context: ./Cluster
    ports:
      - "8083:8083"
    environment:
      - SERVER_PORT=8083
      - SERVICE_NAME=node3
      - ZOOKEPER_HOST=zoo
  node4:
    stop_grace_period: 0s
    build:
      dockerfile: Dockerfile
      context: ./Cluster
    ports:
      - "8084:8084"
    environment:
      - SERVER_PORT=8084
      - SERVICE_NAME=node4
      - ZOOKEPER_HOST=zoo
  zoo:
    image: zookeeper:3.4
    restart: always
    hostname: zoo1
    ports:
      - "2181:2181"
    environment:
      - ZOO_TICK_TIME=100





